/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mykingdom.downloader;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name = "Downloader", id = "com.mykingdom.downloader")
public class DownloaderModule extends KrollModule {

	// Standard Debugging variables
	private static final String TAG = "DownloaderModule";

	// Static Properties
	public static final String PROPERTY_FILES_TO_DOWNLOAD = "filesToDownload";
	public static final String PROPERTY_OUTPUT_DIRECTORY = "outputDirectory";
	public static final String PROPERTY_ENABLE_NOTIFICATION = "enableNotification";
	public static final String PROPERTY_NOTIFICATION_ID = "notificationId";
	public static final String PROPERTY_NOTIFICATION_TITLE = "notificationTitle";
	public static final String PROPERTY_USE_CACHE = "useCache";

	public DownloaderModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(TAG, "inside onAppCreate");
	}
}
